# Test del metodo de la potencia
## Compilamos Metnum

In [40]:
!cd .. && mkdir build
!cd ../build/ && rm -rf *
!cd ../build && cmake \
  -DPYTHON_EXECUTABLE="$(which python)" \
  -DCMAKE_BUILD_TYPE=Release ..
!cd ../build && make install

mkdir: cannot create directory ‘build’: File exists
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Release mode
-- Found PythonInterp: /home/leandro/Downloads/MetodosNumericos/MetodosTp2/metnum-tp2-2c2020/virtualEnvTp2/bin/python (found version "3.6.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- pybind11 v2.2.4
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
CMAKE_INSTALL_PREFIX=/home/leandro

# Test del Metodo de la potencia

In [41]:
!pwd
!python --version
import metnum

/home/leandro/Downloads/MetodosNumericos/MetodosTp2FinalVer/MetNum/tp2/notebooks
Python 3.6.9


# Testeamos el cálculo de autovalores y autovectores

In [42]:
import numpy as np

In [43]:
M = np.array([
    [77, 0],
    [0, 55]
])
autovalores_posta = np.linalg.eig(M)[0]
autovalores_posta = -np.sort(-autovalores_posta) #  Ordenamos autovalores

autovalores_propios, V = metnum.get_first_eigenvalues(M, 2)

assert np.allclose(autovalores_posta, autovalores_propios)
assert np.allclose(V @ np.diag(autovalores_propios) @ V.T, M)

In [44]:
M = np.array([
    [7, 1],
    [1, 9]
])
autovalores_posta = np.linalg.eig(M)[0]
autovalores_posta = -np.sort(-autovalores_posta) #  Ordenamos autovalores de forma creciente

autovalores, V = metnum.get_first_eigenvalues(M, 2)

assert np.allclose(autovalores_posta, autovalores)
assert np.allclose(V @ np.diag(autovalores) @ V.T, M)

In [45]:
M = np.array([
    [6, 0, 2, 0, 5],
    [0, 5, 2, 1, 0],
    [2, 2, 4, 0, 2],
    [0, 1, 0, 9, 0],
    [5, 0, 2, 0, 4]
])
autovalores_posta = np.linalg.eig(M)[0]
autovalores_posta = -np.sort(-autovalores_posta) # ordenamos los autovalores de mayor a menor

autovalores, V = metnum.get_first_eigenvalues(M, 5)

assert np.allclose(autovalores_posta, autovalores)
assert np.allclose(V @ np.diag(autovalores) @ V.T, M)

In [74]:
M = np.random.randint(10, size=(500, 500)) # Se crea una matriz random de 500x500 con valores entre 0 y 9 inclusive.
print(M)

M = M @ M.T # La multiplico por sí misma transpuesta para que sea simétrica.
autovalores_posta = np.linalg.eig(M)[0]
autovalores_posta = -np.sort(-autovalores_posta) # Ordenamos autovalores de mayor a menor

alpha = 10
autovalores, V = metnum.get_first_eigenvalues(M, alpha) # Veamos los primeros valores, ya que esto es lo que vamos a hacer en PCA.

assert np.allclose(autovalores_posta[:alpha], autovalores)
assert np.allclose(M @ V, V @ np.diag(autovalores))

[[6 2 9 ... 8 1 0]
 [4 7 1 ... 5 0 8]
 [9 8 5 ... 3 6 5]
 ...
 [5 0 5 ... 0 6 2]
 [9 8 1 ... 6 2 4]
 [3 6 3 ... 6 7 0]]
